# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Contents')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date Published')),
                ('pics', models.ImageField(upload_to='images/news/%Y/%m/%d/', verbose_name='News Pictures')),
                ('ref_link', models.URLField(verbose_name='URL Reference')),
                ('LanguageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Language.language', verbose_name='Language')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Types')),
            ],
        ),
        migrations.AddField(
            model_name='new',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.Type', verbose_name='Types'),
        ),
    ]
