# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Language', '0001_initial'),
        ('News', '0002_auto_20160619_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Types')),
                ('LanguageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Language.language', verbose_name='Language')),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='pics',
            field=models.ImageField(upload_to='%Y/%m/%d/', verbose_name='News Pictures'),
        ),
        migrations.AlterField(
            model_name='news',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.NewsType', verbose_name='Types'),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
