# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryWebSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255, verbose_name='Title')),
                ('LanguageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Language.language', verbose_name='Language')),
            ],
        ),
        migrations.CreateModel(
            name='WebSiteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255, verbose_name='Title')),
                ('URL', models.CharField(max_length=255, verbose_name='URL')),
                ('Views', models.CharField(max_length=255, verbose_name='Views')),
                ('Descriptions', models.TextField(verbose_name='Descriptions')),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebSite.CategoryWebSite', verbose_name='Category')),
                ('Language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Language.language', verbose_name='Language')),
            ],
        ),
    ]
