# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255, verbose_name='Title')),
                ('Descriptions', models.TextField(verbose_name='Meta Descriptions')),
                ('Keywords', models.CharField(max_length=255, verbose_name='Meta Keywords')),
                ('Text', models.TextField(verbose_name='Text')),
                ('LanguageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Language.language', verbose_name='Language')),
            ],
        ),
        migrations.CreateModel(
            name='TVProgramm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(max_length=255, verbose_name='Title')),
                ('Descriptions', models.TextField(verbose_name='Meta Descriptions')),
                ('LanguageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Language.language', verbose_name='Language')),
                ('TVID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TVProgramm.TVList', verbose_name='TV name')),
            ],
        ),
    ]
