# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255, verbose_name='Title')),
                ('LanguageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Language.language', verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=255, verbose_name='Company Name')),
                ('company_description', models.TextField(verbose_name='Company Description')),
                ('company_text', models.TextField(verbose_name='Company Text')),
                ('company_site', models.CharField(max_length=255, verbose_name='Company Site')),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyList.CategoryCompany', verbose_name='Category')),
                ('Language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Language.language', verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Company List',
                'verbose_name_plural': 'Company List',
            },
        ),
    ]
