# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=255, verbose_name='Car Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('pictures', models.ImageField(upload_to='%Y/%m/%d/', verbose_name='Car Pictures')),
                ('reference_link', models.URLField(verbose_name='Source URL')),
                ('LanguageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Language.language', verbose_name='Language')),
            ],
        ),
        migrations.CreateModel(
            name='CarsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('LanguageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Language.language', verbose_name='Language')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cars.CarsType', verbose_name='Type'),
        ),
    ]
