# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='CountryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255, verbose_name='Title')),
                ('LanguageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Language.language', verbose_name='Language')),
            ],
        ),
        migrations.CreateModel(
            name='DayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(max_length=255, verbose_name='Day')),
                ('Values', models.CharField(max_length=255, verbose_name='Value')),
                ('CityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Weather.CityList', verbose_name='City')),
                ('LanguageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Language.language', verbose_name='Language')),
            ],
        ),
        migrations.AddField(
            model_name='citylist',
            name='CountryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Weather.CountryList', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='citylist',
            name='LanguageID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Language.language', verbose_name='Language'),
        ),
    ]
