# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Movie Title')),
                ('desc', models.TextField(verbose_name='Movie Description')),
                ('pictures', models.ImageField(upload_to='images/news/%Y/%m/%d/', verbose_name='Movie Pictures')),
                ('country', models.CharField(max_length=255, verbose_name='Origin Country')),
                ('producer', models.CharField(max_length=255, verbose_name='Producer')),
                ('scenario', models.TextField(verbose_name='Scenario')),
                ('operator', models.CharField(max_length=255, verbose_name='Operator')),
                ('composer', models.CharField(max_length=255, verbose_name='Composer')),
                ('artists', models.TextField(verbose_name='Artists')),
                ('editor', models.CharField(max_length=255, verbose_name='Editor')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Budget')),
                ('allowed_age', models.IntegerField(verbose_name='Allowed Age')),
                ('mpaa_rating', models.IntegerField(verbose_name='MPAA Rating')),
                ('duration', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Duration')),
                ('imdb_rating', models.IntegerField(verbose_name='IMDB Rating')),
                ('release_date', models.DateField(verbose_name='Release Date')),
                ('reference_link', models.URLField(verbose_name='Reference URL')),
            ],
            options={
                'verbose_name': 'Movies',
                'verbose_name_plural': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='MovieTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Movie Types',
                'verbose_name_plural': 'Movie Types',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.MovieTypes'),
        ),
    ]
