# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='pictures',
            field=models.ImageField(upload_to='Movies/%Y/%m/%d/', verbose_name='Movie Pictures'),
        ),
    ]
